// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: test.proto

#include "test.pb.h"
#include "test.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/method_handler_impl.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace test {

static const char* Test_method_names[] = {
  "/test.Test/TestOpen",
};

std::unique_ptr< Test::Stub> Test::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< Test::Stub> stub(new Test::Stub(channel));
  return stub;
}

Test::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_TestOpen_(Test_method_names[0], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status Test::Stub::TestOpen(::grpc::ClientContext* context, const ::test::OpenSend& request, ::test::OpenReply* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_TestOpen_, context, request, response);
}

void Test::Stub::experimental_async::TestOpen(::grpc::ClientContext* context, const ::test::OpenSend* request, ::test::OpenReply* response, std::function<void(::grpc::Status)> f) {
  return ::grpc::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_TestOpen_, context, request, response, std::move(f));
}

void Test::Stub::experimental_async::TestOpen(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::test::OpenReply* response, std::function<void(::grpc::Status)> f) {
  return ::grpc::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_TestOpen_, context, request, response, std::move(f));
}

::grpc::ClientAsyncResponseReader< ::test::OpenReply>* Test::Stub::AsyncTestOpenRaw(::grpc::ClientContext* context, const ::test::OpenSend& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::test::OpenReply>::Create(channel_.get(), cq, rpcmethod_TestOpen_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::test::OpenReply>* Test::Stub::PrepareAsyncTestOpenRaw(::grpc::ClientContext* context, const ::test::OpenSend& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::test::OpenReply>::Create(channel_.get(), cq, rpcmethod_TestOpen_, context, request, false);
}

Test::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Test_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Test::Service, ::test::OpenSend, ::test::OpenReply>(
          std::mem_fn(&Test::Service::TestOpen), this)));
}

Test::Service::~Service() {
}

::grpc::Status Test::Service::TestOpen(::grpc::ServerContext* context, const ::test::OpenSend* request, ::test::OpenReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace test

