// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: os_remote.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_os_5fremote_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_os_5fremote_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3008000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3008000 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_os_5fremote_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_os_5fremote_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[2]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_os_5fremote_2eproto;
namespace os_remote {
class ArgReply;
class ArgReplyDefaultTypeInternal;
extern ArgReplyDefaultTypeInternal _ArgReply_default_instance_;
class ArgRequest;
class ArgRequestDefaultTypeInternal;
extern ArgRequestDefaultTypeInternal _ArgRequest_default_instance_;
}  // namespace os_remote
PROTOBUF_NAMESPACE_OPEN
template<> ::os_remote::ArgReply* Arena::CreateMaybeMessage<::os_remote::ArgReply>(Arena*);
template<> ::os_remote::ArgRequest* Arena::CreateMaybeMessage<::os_remote::ArgRequest>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace os_remote {

// ===================================================================

class ArgRequest :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:os_remote.ArgRequest) */ {
 public:
  ArgRequest();
  virtual ~ArgRequest();

  ArgRequest(const ArgRequest& from);
  ArgRequest(ArgRequest&& from) noexcept
    : ArgRequest() {
    *this = ::std::move(from);
  }

  inline ArgRequest& operator=(const ArgRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline ArgRequest& operator=(ArgRequest&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const ArgRequest& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ArgRequest* internal_default_instance() {
    return reinterpret_cast<const ArgRequest*>(
               &_ArgRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(ArgRequest* other);
  friend void swap(ArgRequest& a, ArgRequest& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline ArgRequest* New() const final {
    return CreateMaybeMessage<ArgRequest>(nullptr);
  }

  ArgRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<ArgRequest>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const ArgRequest& from);
  void MergeFrom(const ArgRequest& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  #else
  bool MergePartialFromCodedStream(
      ::PROTOBUF_NAMESPACE_ID::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::PROTOBUF_NAMESPACE_ID::io::CodedOutputStream* output) const final;
  ::PROTOBUF_NAMESPACE_ID::uint8* InternalSerializeWithCachedSizesToArray(
      ::PROTOBUF_NAMESPACE_ID::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ArgRequest* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "os_remote.ArgRequest";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_os_5fremote_2eproto);
    return ::descriptor_table_os_5fremote_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // bytes inarg = 1;
  void clear_inarg();
  static const int kInargFieldNumber = 1;
  const std::string& inarg() const;
  void set_inarg(const std::string& value);
  void set_inarg(std::string&& value);
  void set_inarg(const char* value);
  void set_inarg(const void* value, size_t size);
  std::string* mutable_inarg();
  std::string* release_inarg();
  void set_allocated_inarg(std::string* inarg);

  // uint32 outlen = 2;
  void clear_outlen();
  static const int kOutlenFieldNumber = 2;
  ::PROTOBUF_NAMESPACE_ID::uint32 outlen() const;
  void set_outlen(::PROTOBUF_NAMESPACE_ID::uint32 value);

  // @@protoc_insertion_point(class_scope:os_remote.ArgRequest)
 private:
  class HasBitSetters;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr inarg_;
  ::PROTOBUF_NAMESPACE_ID::uint32 outlen_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_os_5fremote_2eproto;
};
// -------------------------------------------------------------------

class ArgReply :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:os_remote.ArgReply) */ {
 public:
  ArgReply();
  virtual ~ArgReply();

  ArgReply(const ArgReply& from);
  ArgReply(ArgReply&& from) noexcept
    : ArgReply() {
    *this = ::std::move(from);
  }

  inline ArgReply& operator=(const ArgReply& from) {
    CopyFrom(from);
    return *this;
  }
  inline ArgReply& operator=(ArgReply&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const ArgReply& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ArgReply* internal_default_instance() {
    return reinterpret_cast<const ArgReply*>(
               &_ArgReply_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  void Swap(ArgReply* other);
  friend void swap(ArgReply& a, ArgReply& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline ArgReply* New() const final {
    return CreateMaybeMessage<ArgReply>(nullptr);
  }

  ArgReply* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<ArgReply>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const ArgReply& from);
  void MergeFrom(const ArgReply& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  #else
  bool MergePartialFromCodedStream(
      ::PROTOBUF_NAMESPACE_ID::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::PROTOBUF_NAMESPACE_ID::io::CodedOutputStream* output) const final;
  ::PROTOBUF_NAMESPACE_ID::uint8* InternalSerializeWithCachedSizesToArray(
      ::PROTOBUF_NAMESPACE_ID::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ArgReply* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "os_remote.ArgReply";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_os_5fremote_2eproto);
    return ::descriptor_table_os_5fremote_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // bytes outarg = 1;
  void clear_outarg();
  static const int kOutargFieldNumber = 1;
  const std::string& outarg() const;
  void set_outarg(const std::string& value);
  void set_outarg(std::string&& value);
  void set_outarg(const char* value);
  void set_outarg(const void* value, size_t size);
  std::string* mutable_outarg();
  std::string* release_outarg();
  void set_allocated_outarg(std::string* outarg);

  // @@protoc_insertion_point(class_scope:os_remote.ArgReply)
 private:
  class HasBitSetters;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr outarg_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_os_5fremote_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// ArgRequest

// bytes inarg = 1;
inline void ArgRequest::clear_inarg() {
  inarg_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline const std::string& ArgRequest::inarg() const {
  // @@protoc_insertion_point(field_get:os_remote.ArgRequest.inarg)
  return inarg_.GetNoArena();
}
inline void ArgRequest::set_inarg(const std::string& value) {
  
  inarg_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:os_remote.ArgRequest.inarg)
}
inline void ArgRequest::set_inarg(std::string&& value) {
  
  inarg_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:os_remote.ArgRequest.inarg)
}
inline void ArgRequest::set_inarg(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  inarg_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:os_remote.ArgRequest.inarg)
}
inline void ArgRequest::set_inarg(const void* value, size_t size) {
  
  inarg_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:os_remote.ArgRequest.inarg)
}
inline std::string* ArgRequest::mutable_inarg() {
  
  // @@protoc_insertion_point(field_mutable:os_remote.ArgRequest.inarg)
  return inarg_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* ArgRequest::release_inarg() {
  // @@protoc_insertion_point(field_release:os_remote.ArgRequest.inarg)
  
  return inarg_.ReleaseNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void ArgRequest::set_allocated_inarg(std::string* inarg) {
  if (inarg != nullptr) {
    
  } else {
    
  }
  inarg_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), inarg);
  // @@protoc_insertion_point(field_set_allocated:os_remote.ArgRequest.inarg)
}

// uint32 outlen = 2;
inline void ArgRequest::clear_outlen() {
  outlen_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 ArgRequest::outlen() const {
  // @@protoc_insertion_point(field_get:os_remote.ArgRequest.outlen)
  return outlen_;
}
inline void ArgRequest::set_outlen(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  outlen_ = value;
  // @@protoc_insertion_point(field_set:os_remote.ArgRequest.outlen)
}

// -------------------------------------------------------------------

// ArgReply

// bytes outarg = 1;
inline void ArgReply::clear_outarg() {
  outarg_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline const std::string& ArgReply::outarg() const {
  // @@protoc_insertion_point(field_get:os_remote.ArgReply.outarg)
  return outarg_.GetNoArena();
}
inline void ArgReply::set_outarg(const std::string& value) {
  
  outarg_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:os_remote.ArgReply.outarg)
}
inline void ArgReply::set_outarg(std::string&& value) {
  
  outarg_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:os_remote.ArgReply.outarg)
}
inline void ArgReply::set_outarg(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  outarg_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:os_remote.ArgReply.outarg)
}
inline void ArgReply::set_outarg(const void* value, size_t size) {
  
  outarg_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:os_remote.ArgReply.outarg)
}
inline std::string* ArgReply::mutable_outarg() {
  
  // @@protoc_insertion_point(field_mutable:os_remote.ArgReply.outarg)
  return outarg_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* ArgReply::release_outarg() {
  // @@protoc_insertion_point(field_release:os_remote.ArgReply.outarg)
  
  return outarg_.ReleaseNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void ArgReply::set_allocated_outarg(std::string* outarg) {
  if (outarg != nullptr) {
    
  } else {
    
  }
  outarg_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), outarg);
  // @@protoc_insertion_point(field_set_allocated:os_remote.ArgReply.outarg)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace os_remote

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_os_5fremote_2eproto
