// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: os_remote.proto

#include "os_remote.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
namespace os_remote {
class ArgRequestDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<ArgRequest> _instance;
} _ArgRequest_default_instance_;
class ArgReplyDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<ArgReply> _instance;
} _ArgReply_default_instance_;
}  // namespace os_remote
static void InitDefaultsscc_info_ArgReply_os_5fremote_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::os_remote::_ArgReply_default_instance_;
    new (ptr) ::os_remote::ArgReply();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::os_remote::ArgReply::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_ArgReply_os_5fremote_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsscc_info_ArgReply_os_5fremote_2eproto}, {}};

static void InitDefaultsscc_info_ArgRequest_os_5fremote_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::os_remote::_ArgRequest_default_instance_;
    new (ptr) ::os_remote::ArgRequest();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::os_remote::ArgRequest::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_ArgRequest_os_5fremote_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsscc_info_ArgRequest_os_5fremote_2eproto}, {}};

static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_os_5fremote_2eproto[2];
static constexpr ::PROTOBUF_NAMESPACE_ID::EnumDescriptor const** file_level_enum_descriptors_os_5fremote_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_os_5fremote_2eproto = nullptr;

const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_os_5fremote_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::os_remote::ArgRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::os_remote::ArgRequest, inarg_),
  PROTOBUF_FIELD_OFFSET(::os_remote::ArgRequest, outlen_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::os_remote::ArgReply, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::os_remote::ArgReply, outarg_),
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::os_remote::ArgRequest)},
  { 7, -1, sizeof(::os_remote::ArgReply)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::os_remote::_ArgRequest_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::os_remote::_ArgReply_default_instance_),
};

const char descriptor_table_protodef_os_5fremote_2eproto[] =
  "\n\017os_remote.proto\022\tos_remote\"+\n\nArgReque"
  "st\022\r\n\005inarg\030\001 \001(\014\022\016\n\006outlen\030\002 \001(\r\"\032\n\010Arg"
  "Reply\022\016\n\006outarg\030\001 \001(\0142\203\013\n\010OSRemote\0224\n\004In"
  "it\022\025.os_remote.ArgRequest\032\023.os_remote.Ar"
  "gReply\"\000\0224\n\004Open\022\025.os_remote.ArgRequest\032"
  "\023.os_remote.ArgReply\"\000\0226\n\006Delete\022\025.os_re"
  "mote.ArgRequest\032\023.os_remote.ArgReply\"\000\0226"
  "\n\006Access\022\025.os_remote.ArgRequest\032\023.os_rem"
  "ote.ArgReply\"\000\022<\n\014FullPathname\022\025.os_remo"
  "te.ArgRequest\032\023.os_remote.ArgReply\"\000\022:\n\n"
  "Randomness\022\025.os_remote.ArgRequest\032\023.os_r"
  "emote.ArgReply\"\000\0225\n\005Sleep\022\025.os_remote.Ar"
  "gRequest\032\023.os_remote.ArgReply\"\000\022;\n\013Curre"
  "ntTime\022\025.os_remote.ArgRequest\032\023.os_remot"
  "e.ArgReply\"\000\022<\n\014GetLastError\022\025.os_remote"
  ".ArgRequest\032\023.os_remote.ArgReply\"\000\022@\n\020Cu"
  "rrentTimeInt64\022\025.os_remote.ArgRequest\032\023."
  "os_remote.ArgReply\"\000\0225\n\005Write\022\025.os_remot"
  "e.ArgRequest\032\023.os_remote.ArgReply\"\000\0224\n\004R"
  "ead\022\025.os_remote.ArgRequest\032\023.os_remote.A"
  "rgReply\"\000\0228\n\010Truncate\022\025.os_remote.ArgReq"
  "uest\032\023.os_remote.ArgReply\"\000\0224\n\004Sync\022\025.os"
  "_remote.ArgRequest\032\023.os_remote.ArgReply\""
  "\000\0228\n\010FileSize\022\025.os_remote.ArgRequest\032\023.o"
  "s_remote.ArgReply\"\000\022;\n\013FileControl\022\025.os_"
  "remote.ArgRequest\032\023.os_remote.ArgReply\"\000"
  "\022:\n\nSectorSize\022\025.os_remote.ArgRequest\032\023."
  "os_remote.ArgReply\"\000\022E\n\025DeviceCharacteri"
  "stics\022\025.os_remote.ArgRequest\032\023.os_remote"
  ".ArgReply\"\000\0225\n\005Close\022\025.os_remote.ArgRequ"
  "est\032\023.os_remote.ArgReply\"\000\0224\n\004Lock\022\025.os_"
  "remote.ArgRequest\032\023.os_remote.ArgReply\"\000"
  "\0226\n\006Unlock\022\025.os_remote.ArgRequest\032\023.os_r"
  "emote.ArgReply\"\000\022A\n\021CheckReservedLock\022\025."
  "os_remote.ArgRequest\032\023.os_remote.ArgRepl"
  "y\"\000\0225\n\005Fetch\022\025.os_remote.ArgRequest\032\023.os"
  "_remote.ArgReply\"\000\0227\n\007Unfetch\022\025.os_remot"
  "e.ArgRequest\032\023.os_remote.ArgReply\"\000b\006pro"
  "to3"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_os_5fremote_2eproto_deps[1] = {
};
static ::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase*const descriptor_table_os_5fremote_2eproto_sccs[2] = {
  &scc_info_ArgReply_os_5fremote_2eproto.base,
  &scc_info_ArgRequest_os_5fremote_2eproto.base,
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_os_5fremote_2eproto_once;
static bool descriptor_table_os_5fremote_2eproto_initialized = false;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_os_5fremote_2eproto = {
  &descriptor_table_os_5fremote_2eproto_initialized, descriptor_table_protodef_os_5fremote_2eproto, "os_remote.proto", 1523,
  &descriptor_table_os_5fremote_2eproto_once, descriptor_table_os_5fremote_2eproto_sccs, descriptor_table_os_5fremote_2eproto_deps, 2, 0,
  schemas, file_default_instances, TableStruct_os_5fremote_2eproto::offsets,
  file_level_metadata_os_5fremote_2eproto, 2, file_level_enum_descriptors_os_5fremote_2eproto, file_level_service_descriptors_os_5fremote_2eproto,
};

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_os_5fremote_2eproto = (  ::PROTOBUF_NAMESPACE_ID::internal::AddDescriptors(&descriptor_table_os_5fremote_2eproto), true);
namespace os_remote {

// ===================================================================

void ArgRequest::InitAsDefaultInstance() {
}
class ArgRequest::HasBitSetters {
 public:
};

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int ArgRequest::kInargFieldNumber;
const int ArgRequest::kOutlenFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

ArgRequest::ArgRequest()
  : ::PROTOBUF_NAMESPACE_ID::Message(), _internal_metadata_(nullptr) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:os_remote.ArgRequest)
}
ArgRequest::ArgRequest(const ArgRequest& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      _internal_metadata_(nullptr) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  inarg_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (from.inarg().size() > 0) {
    inarg_.AssignWithDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from.inarg_);
  }
  outlen_ = from.outlen_;
  // @@protoc_insertion_point(copy_constructor:os_remote.ArgRequest)
}

void ArgRequest::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_ArgRequest_os_5fremote_2eproto.base);
  inarg_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  outlen_ = 0u;
}

ArgRequest::~ArgRequest() {
  // @@protoc_insertion_point(destructor:os_remote.ArgRequest)
  SharedDtor();
}

void ArgRequest::SharedDtor() {
  inarg_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

void ArgRequest::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ArgRequest& ArgRequest::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_ArgRequest_os_5fremote_2eproto.base);
  return *internal_default_instance();
}


void ArgRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:os_remote.ArgRequest)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  inarg_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  outlen_ = 0u;
  _internal_metadata_.Clear();
}

#if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
const char* ArgRequest::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // bytes inarg = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(mutable_inarg(), ptr, ctx);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // uint32 outlen = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 16)) {
          outlen_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag, &_internal_metadata_, ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}
#else  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
bool ArgRequest::MergePartialFromCodedStream(
    ::PROTOBUF_NAMESPACE_ID::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!PROTOBUF_PREDICT_TRUE(EXPRESSION)) goto failure
  ::PROTOBUF_NAMESPACE_ID::uint32 tag;
  // @@protoc_insertion_point(parse_start:os_remote.ArgRequest)
  for (;;) {
    ::std::pair<::PROTOBUF_NAMESPACE_ID::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // bytes inarg = 1;
      case 1: {
        if (static_cast< ::PROTOBUF_NAMESPACE_ID::uint8>(tag) == (10 & 0xFF)) {
          DO_(::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::ReadBytes(
                input, this->mutable_inarg()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // uint32 outlen = 2;
      case 2: {
        if (static_cast< ::PROTOBUF_NAMESPACE_ID::uint8>(tag) == (16 & 0xFF)) {

          DO_((::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::ReadPrimitive<
                   ::PROTOBUF_NAMESPACE_ID::uint32, ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_UINT32>(
                 input, &outlen_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::PROTOBUF_NAMESPACE_ID::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:os_remote.ArgRequest)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:os_remote.ArgRequest)
  return false;
#undef DO_
}
#endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER

void ArgRequest::SerializeWithCachedSizes(
    ::PROTOBUF_NAMESPACE_ID::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:os_remote.ArgRequest)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // bytes inarg = 1;
  if (this->inarg().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteBytesMaybeAliased(
      1, this->inarg(), output);
  }

  // uint32 outlen = 2;
  if (this->outlen() != 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt32(2, this->outlen(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:os_remote.ArgRequest)
}

::PROTOBUF_NAMESPACE_ID::uint8* ArgRequest::InternalSerializeWithCachedSizesToArray(
    ::PROTOBUF_NAMESPACE_ID::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:os_remote.ArgRequest)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // bytes inarg = 1;
  if (this->inarg().size() > 0) {
    target =
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteBytesToArray(
        1, this->inarg(), target);
  }

  // uint32 outlen = 2;
  if (this->outlen() != 0) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt32ToArray(2, this->outlen(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:os_remote.ArgRequest)
  return target;
}

size_t ArgRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:os_remote.ArgRequest)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // bytes inarg = 1;
  if (this->inarg().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
        this->inarg());
  }

  // uint32 outlen = 2;
  if (this->outlen() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt32Size(
        this->outlen());
  }

  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void ArgRequest::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:os_remote.ArgRequest)
  GOOGLE_DCHECK_NE(&from, this);
  const ArgRequest* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<ArgRequest>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:os_remote.ArgRequest)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:os_remote.ArgRequest)
    MergeFrom(*source);
  }
}

void ArgRequest::MergeFrom(const ArgRequest& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:os_remote.ArgRequest)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.inarg().size() > 0) {

    inarg_.AssignWithDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from.inarg_);
  }
  if (from.outlen() != 0) {
    set_outlen(from.outlen());
  }
}

void ArgRequest::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:os_remote.ArgRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ArgRequest::CopyFrom(const ArgRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:os_remote.ArgRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ArgRequest::IsInitialized() const {
  return true;
}

void ArgRequest::Swap(ArgRequest* other) {
  if (other == this) return;
  InternalSwap(other);
}
void ArgRequest::InternalSwap(ArgRequest* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
  inarg_.Swap(&other->inarg_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  swap(outlen_, other->outlen_);
}

::PROTOBUF_NAMESPACE_ID::Metadata ArgRequest::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

void ArgReply::InitAsDefaultInstance() {
}
class ArgReply::HasBitSetters {
 public:
};

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int ArgReply::kOutargFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

ArgReply::ArgReply()
  : ::PROTOBUF_NAMESPACE_ID::Message(), _internal_metadata_(nullptr) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:os_remote.ArgReply)
}
ArgReply::ArgReply(const ArgReply& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      _internal_metadata_(nullptr) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  outarg_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (from.outarg().size() > 0) {
    outarg_.AssignWithDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from.outarg_);
  }
  // @@protoc_insertion_point(copy_constructor:os_remote.ArgReply)
}

void ArgReply::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_ArgReply_os_5fremote_2eproto.base);
  outarg_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

ArgReply::~ArgReply() {
  // @@protoc_insertion_point(destructor:os_remote.ArgReply)
  SharedDtor();
}

void ArgReply::SharedDtor() {
  outarg_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

void ArgReply::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ArgReply& ArgReply::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_ArgReply_os_5fremote_2eproto.base);
  return *internal_default_instance();
}


void ArgReply::Clear() {
// @@protoc_insertion_point(message_clear_start:os_remote.ArgReply)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  outarg_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  _internal_metadata_.Clear();
}

#if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
const char* ArgReply::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // bytes outarg = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(mutable_outarg(), ptr, ctx);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag, &_internal_metadata_, ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}
#else  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
bool ArgReply::MergePartialFromCodedStream(
    ::PROTOBUF_NAMESPACE_ID::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!PROTOBUF_PREDICT_TRUE(EXPRESSION)) goto failure
  ::PROTOBUF_NAMESPACE_ID::uint32 tag;
  // @@protoc_insertion_point(parse_start:os_remote.ArgReply)
  for (;;) {
    ::std::pair<::PROTOBUF_NAMESPACE_ID::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // bytes outarg = 1;
      case 1: {
        if (static_cast< ::PROTOBUF_NAMESPACE_ID::uint8>(tag) == (10 & 0xFF)) {
          DO_(::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::ReadBytes(
                input, this->mutable_outarg()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::PROTOBUF_NAMESPACE_ID::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:os_remote.ArgReply)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:os_remote.ArgReply)
  return false;
#undef DO_
}
#endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER

void ArgReply::SerializeWithCachedSizes(
    ::PROTOBUF_NAMESPACE_ID::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:os_remote.ArgReply)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // bytes outarg = 1;
  if (this->outarg().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteBytesMaybeAliased(
      1, this->outarg(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:os_remote.ArgReply)
}

::PROTOBUF_NAMESPACE_ID::uint8* ArgReply::InternalSerializeWithCachedSizesToArray(
    ::PROTOBUF_NAMESPACE_ID::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:os_remote.ArgReply)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // bytes outarg = 1;
  if (this->outarg().size() > 0) {
    target =
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteBytesToArray(
        1, this->outarg(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:os_remote.ArgReply)
  return target;
}

size_t ArgReply::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:os_remote.ArgReply)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // bytes outarg = 1;
  if (this->outarg().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
        this->outarg());
  }

  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void ArgReply::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:os_remote.ArgReply)
  GOOGLE_DCHECK_NE(&from, this);
  const ArgReply* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<ArgReply>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:os_remote.ArgReply)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:os_remote.ArgReply)
    MergeFrom(*source);
  }
}

void ArgReply::MergeFrom(const ArgReply& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:os_remote.ArgReply)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.outarg().size() > 0) {

    outarg_.AssignWithDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from.outarg_);
  }
}

void ArgReply::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:os_remote.ArgReply)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ArgReply::CopyFrom(const ArgReply& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:os_remote.ArgReply)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ArgReply::IsInitialized() const {
  return true;
}

void ArgReply::Swap(ArgReply* other) {
  if (other == this) return;
  InternalSwap(other);
}
void ArgReply::InternalSwap(ArgReply* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
  outarg_.Swap(&other->outarg_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
}

::PROTOBUF_NAMESPACE_ID::Metadata ArgReply::GetMetadata() const {
  return GetMetadataStatic();
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace os_remote
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::os_remote::ArgRequest* Arena::CreateMaybeMessage< ::os_remote::ArgRequest >(Arena* arena) {
  return Arena::CreateInternal< ::os_remote::ArgRequest >(arena);
}
template<> PROTOBUF_NOINLINE ::os_remote::ArgReply* Arena::CreateMaybeMessage< ::os_remote::ArgReply >(Arena* arena) {
  return Arena::CreateInternal< ::os_remote::ArgReply >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
