// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: os_remote.proto

#include "os_remote.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

namespace os_remote {
class ArgRequestDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<ArgRequest> _instance;
} _ArgRequest_default_instance_;
class ArgReplyDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<ArgReply> _instance;
} _ArgReply_default_instance_;
}  // namespace os_remote
static void InitDefaultsArgRequest_os_5fremote_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::os_remote::_ArgRequest_default_instance_;
    new (ptr) ::os_remote::ArgRequest();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::os_remote::ArgRequest::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_ArgRequest_os_5fremote_2eproto =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsArgRequest_os_5fremote_2eproto}, {}};

static void InitDefaultsArgReply_os_5fremote_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::os_remote::_ArgReply_default_instance_;
    new (ptr) ::os_remote::ArgReply();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::os_remote::ArgReply::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_ArgReply_os_5fremote_2eproto =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsArgReply_os_5fremote_2eproto}, {}};

void InitDefaults_os_5fremote_2eproto() {
  ::google::protobuf::internal::InitSCC(&scc_info_ArgRequest_os_5fremote_2eproto.base);
  ::google::protobuf::internal::InitSCC(&scc_info_ArgReply_os_5fremote_2eproto.base);
}

::google::protobuf::Metadata file_level_metadata_os_5fremote_2eproto[2];
constexpr ::google::protobuf::EnumDescriptor const** file_level_enum_descriptors_os_5fremote_2eproto = nullptr;
constexpr ::google::protobuf::ServiceDescriptor const** file_level_service_descriptors_os_5fremote_2eproto = nullptr;

const ::google::protobuf::uint32 TableStruct_os_5fremote_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::os_remote::ArgRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::os_remote::ArgRequest, inarg_),
  PROTOBUF_FIELD_OFFSET(::os_remote::ArgRequest, outlen_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::os_remote::ArgReply, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::os_remote::ArgReply, outarg_),
};
static const ::google::protobuf::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::os_remote::ArgRequest)},
  { 7, -1, sizeof(::os_remote::ArgReply)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::os_remote::_ArgRequest_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::os_remote::_ArgReply_default_instance_),
};

::google::protobuf::internal::AssignDescriptorsTable assign_descriptors_table_os_5fremote_2eproto = {
  {}, AddDescriptors_os_5fremote_2eproto, "os_remote.proto", schemas,
  file_default_instances, TableStruct_os_5fremote_2eproto::offsets,
  file_level_metadata_os_5fremote_2eproto, 2, file_level_enum_descriptors_os_5fremote_2eproto, file_level_service_descriptors_os_5fremote_2eproto,
};

const char descriptor_table_protodef_os_5fremote_2eproto[] =
  "\n\017os_remote.proto\022\tos_remote\"+\n\nArgReque"
  "st\022\r\n\005inarg\030\001 \001(\014\022\016\n\006outlen\030\002 \001(\r\"\032\n\010Arg"
  "Reply\022\016\n\006outarg\030\001 \001(\0142\203\013\n\010OSRemote\0224\n\004In"
  "it\022\025.os_remote.ArgRequest\032\023.os_remote.Ar"
  "gReply\"\000\0224\n\004Open\022\025.os_remote.ArgRequest\032"
  "\023.os_remote.ArgReply\"\000\0226\n\006Delete\022\025.os_re"
  "mote.ArgRequest\032\023.os_remote.ArgReply\"\000\0226"
  "\n\006Access\022\025.os_remote.ArgRequest\032\023.os_rem"
  "ote.ArgReply\"\000\022<\n\014FullPathname\022\025.os_remo"
  "te.ArgRequest\032\023.os_remote.ArgReply\"\000\022:\n\n"
  "Randomness\022\025.os_remote.ArgRequest\032\023.os_r"
  "emote.ArgReply\"\000\0225\n\005Sleep\022\025.os_remote.Ar"
  "gRequest\032\023.os_remote.ArgReply\"\000\022;\n\013Curre"
  "ntTime\022\025.os_remote.ArgRequest\032\023.os_remot"
  "e.ArgReply\"\000\022<\n\014GetLastError\022\025.os_remote"
  ".ArgRequest\032\023.os_remote.ArgReply\"\000\022@\n\020Cu"
  "rrentTimeInt64\022\025.os_remote.ArgRequest\032\023."
  "os_remote.ArgReply\"\000\0225\n\005Write\022\025.os_remot"
  "e.ArgRequest\032\023.os_remote.ArgReply\"\000\0224\n\004R"
  "ead\022\025.os_remote.ArgRequest\032\023.os_remote.A"
  "rgReply\"\000\0228\n\010Truncate\022\025.os_remote.ArgReq"
  "uest\032\023.os_remote.ArgReply\"\000\0224\n\004Sync\022\025.os"
  "_remote.ArgRequest\032\023.os_remote.ArgReply\""
  "\000\0228\n\010FileSize\022\025.os_remote.ArgRequest\032\023.o"
  "s_remote.ArgReply\"\000\022;\n\013FileControl\022\025.os_"
  "remote.ArgRequest\032\023.os_remote.ArgReply\"\000"
  "\022:\n\nSectorSize\022\025.os_remote.ArgRequest\032\023."
  "os_remote.ArgReply\"\000\022E\n\025DeviceCharacteri"
  "stics\022\025.os_remote.ArgRequest\032\023.os_remote"
  ".ArgReply\"\000\0225\n\005Close\022\025.os_remote.ArgRequ"
  "est\032\023.os_remote.ArgReply\"\000\0224\n\004Lock\022\025.os_"
  "remote.ArgRequest\032\023.os_remote.ArgReply\"\000"
  "\0226\n\006Unlock\022\025.os_remote.ArgRequest\032\023.os_r"
  "emote.ArgReply\"\000\022A\n\021CheckReservedLock\022\025."
  "os_remote.ArgRequest\032\023.os_remote.ArgRepl"
  "y\"\000\0225\n\005Fetch\022\025.os_remote.ArgRequest\032\023.os"
  "_remote.ArgReply\"\000\0227\n\007Unfetch\022\025.os_remot"
  "e.ArgRequest\032\023.os_remote.ArgReply\"\000b\006pro"
  "to3"
  ;
::google::protobuf::internal::DescriptorTable descriptor_table_os_5fremote_2eproto = {
  false, InitDefaults_os_5fremote_2eproto, 
  descriptor_table_protodef_os_5fremote_2eproto,
  "os_remote.proto", &assign_descriptors_table_os_5fremote_2eproto, 1523,
};

void AddDescriptors_os_5fremote_2eproto() {
  static constexpr ::google::protobuf::internal::InitFunc deps[1] =
  {
  };
 ::google::protobuf::internal::AddDescriptors(&descriptor_table_os_5fremote_2eproto, deps, 0);
}

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_os_5fremote_2eproto = []() { AddDescriptors_os_5fremote_2eproto(); return true; }();
namespace os_remote {

// ===================================================================

void ArgRequest::InitAsDefaultInstance() {
}
class ArgRequest::HasBitSetters {
 public:
};

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int ArgRequest::kInargFieldNumber;
const int ArgRequest::kOutlenFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

ArgRequest::ArgRequest()
  : ::google::protobuf::Message(), _internal_metadata_(nullptr) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:os_remote.ArgRequest)
}
ArgRequest::ArgRequest(const ArgRequest& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(nullptr) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  inarg_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.inarg().size() > 0) {
    inarg_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.inarg_);
  }
  outlen_ = from.outlen_;
  // @@protoc_insertion_point(copy_constructor:os_remote.ArgRequest)
}

void ArgRequest::SharedCtor() {
  ::google::protobuf::internal::InitSCC(
      &scc_info_ArgRequest_os_5fremote_2eproto.base);
  inarg_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  outlen_ = 0u;
}

ArgRequest::~ArgRequest() {
  // @@protoc_insertion_point(destructor:os_remote.ArgRequest)
  SharedDtor();
}

void ArgRequest::SharedDtor() {
  inarg_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void ArgRequest::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ArgRequest& ArgRequest::default_instance() {
  ::google::protobuf::internal::InitSCC(&::scc_info_ArgRequest_os_5fremote_2eproto.base);
  return *internal_default_instance();
}


void ArgRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:os_remote.ArgRequest)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  inarg_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  outlen_ = 0u;
  _internal_metadata_.Clear();
}

#if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
const char* ArgRequest::_InternalParse(const char* begin, const char* end, void* object,
                  ::google::protobuf::internal::ParseContext* ctx) {
  auto msg = static_cast<ArgRequest*>(object);
  ::google::protobuf::int32 size; (void)size;
  int depth; (void)depth;
  ::google::protobuf::uint32 tag;
  ::google::protobuf::internal::ParseFunc parser_till_end; (void)parser_till_end;
  auto ptr = begin;
  while (ptr < end) {
    ptr = ::google::protobuf::io::Parse32(ptr, &tag);
    GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
    switch (tag >> 3) {
      // bytes inarg = 1;
      case 1: {
        if (static_cast<::google::protobuf::uint8>(tag) != 10) goto handle_unusual;
        ptr = ::google::protobuf::io::ReadSize(ptr, &size);
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        object = msg->mutable_inarg();
        if (size > end - ptr + ::google::protobuf::internal::ParseContext::kSlopBytes) {
          parser_till_end = ::google::protobuf::internal::GreedyStringParser;
          goto string_till_end;
        }
        GOOGLE_PROTOBUF_PARSER_ASSERT(::google::protobuf::internal::StringCheck(ptr, size, ctx));
        ::google::protobuf::internal::InlineGreedyStringParser(object, ptr, size, ctx);
        ptr += size;
        break;
      }
      // uint32 outlen = 2;
      case 2: {
        if (static_cast<::google::protobuf::uint8>(tag) != 16) goto handle_unusual;
        msg->set_outlen(::google::protobuf::internal::ReadVarint(&ptr));
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        break;
      }
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->EndGroup(tag);
          return ptr;
        }
        auto res = UnknownFieldParse(tag, {_InternalParse, msg},
          ptr, end, msg->_internal_metadata_.mutable_unknown_fields(), ctx);
        ptr = res.first;
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr != nullptr);
        if (res.second) return ptr;
      }
    }  // switch
  }  // while
  return ptr;
string_till_end:
  static_cast<::std::string*>(object)->clear();
  static_cast<::std::string*>(object)->reserve(size);
  goto len_delim_till_end;
len_delim_till_end:
  return ctx->StoreAndTailCall(ptr, end, {_InternalParse, msg},
                               {parser_till_end, object}, size);
}
#else  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
bool ArgRequest::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!PROTOBUF_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:os_remote.ArgRequest)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // bytes inarg = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (10 & 0xFF)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadBytes(
                input, this->mutable_inarg()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // uint32 outlen = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (16 & 0xFF)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &outlen_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:os_remote.ArgRequest)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:os_remote.ArgRequest)
  return false;
#undef DO_
}
#endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER

void ArgRequest::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:os_remote.ArgRequest)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // bytes inarg = 1;
  if (this->inarg().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBytesMaybeAliased(
      1, this->inarg(), output);
  }

  // uint32 outlen = 2;
  if (this->outlen() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(2, this->outlen(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:os_remote.ArgRequest)
}

::google::protobuf::uint8* ArgRequest::InternalSerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:os_remote.ArgRequest)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // bytes inarg = 1;
  if (this->inarg().size() > 0) {
    target =
      ::google::protobuf::internal::WireFormatLite::WriteBytesToArray(
        1, this->inarg(), target);
  }

  // uint32 outlen = 2;
  if (this->outlen() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(2, this->outlen(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:os_remote.ArgRequest)
  return target;
}

size_t ArgRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:os_remote.ArgRequest)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // bytes inarg = 1;
  if (this->inarg().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::BytesSize(
        this->inarg());
  }

  // uint32 outlen = 2;
  if (this->outlen() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->outlen());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void ArgRequest::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:os_remote.ArgRequest)
  GOOGLE_DCHECK_NE(&from, this);
  const ArgRequest* source =
      ::google::protobuf::DynamicCastToGenerated<ArgRequest>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:os_remote.ArgRequest)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:os_remote.ArgRequest)
    MergeFrom(*source);
  }
}

void ArgRequest::MergeFrom(const ArgRequest& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:os_remote.ArgRequest)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.inarg().size() > 0) {

    inarg_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.inarg_);
  }
  if (from.outlen() != 0) {
    set_outlen(from.outlen());
  }
}

void ArgRequest::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:os_remote.ArgRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ArgRequest::CopyFrom(const ArgRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:os_remote.ArgRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ArgRequest::IsInitialized() const {
  return true;
}

void ArgRequest::Swap(ArgRequest* other) {
  if (other == this) return;
  InternalSwap(other);
}
void ArgRequest::InternalSwap(ArgRequest* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
  inarg_.Swap(&other->inarg_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  swap(outlen_, other->outlen_);
}

::google::protobuf::Metadata ArgRequest::GetMetadata() const {
  ::google::protobuf::internal::AssignDescriptors(&::assign_descriptors_table_os_5fremote_2eproto);
  return ::file_level_metadata_os_5fremote_2eproto[kIndexInFileMessages];
}


// ===================================================================

void ArgReply::InitAsDefaultInstance() {
}
class ArgReply::HasBitSetters {
 public:
};

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int ArgReply::kOutargFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

ArgReply::ArgReply()
  : ::google::protobuf::Message(), _internal_metadata_(nullptr) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:os_remote.ArgReply)
}
ArgReply::ArgReply(const ArgReply& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(nullptr) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  outarg_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.outarg().size() > 0) {
    outarg_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.outarg_);
  }
  // @@protoc_insertion_point(copy_constructor:os_remote.ArgReply)
}

void ArgReply::SharedCtor() {
  ::google::protobuf::internal::InitSCC(
      &scc_info_ArgReply_os_5fremote_2eproto.base);
  outarg_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

ArgReply::~ArgReply() {
  // @@protoc_insertion_point(destructor:os_remote.ArgReply)
  SharedDtor();
}

void ArgReply::SharedDtor() {
  outarg_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void ArgReply::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ArgReply& ArgReply::default_instance() {
  ::google::protobuf::internal::InitSCC(&::scc_info_ArgReply_os_5fremote_2eproto.base);
  return *internal_default_instance();
}


void ArgReply::Clear() {
// @@protoc_insertion_point(message_clear_start:os_remote.ArgReply)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  outarg_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  _internal_metadata_.Clear();
}

#if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
const char* ArgReply::_InternalParse(const char* begin, const char* end, void* object,
                  ::google::protobuf::internal::ParseContext* ctx) {
  auto msg = static_cast<ArgReply*>(object);
  ::google::protobuf::int32 size; (void)size;
  int depth; (void)depth;
  ::google::protobuf::uint32 tag;
  ::google::protobuf::internal::ParseFunc parser_till_end; (void)parser_till_end;
  auto ptr = begin;
  while (ptr < end) {
    ptr = ::google::protobuf::io::Parse32(ptr, &tag);
    GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
    switch (tag >> 3) {
      // bytes outarg = 1;
      case 1: {
        if (static_cast<::google::protobuf::uint8>(tag) != 10) goto handle_unusual;
        ptr = ::google::protobuf::io::ReadSize(ptr, &size);
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        object = msg->mutable_outarg();
        if (size > end - ptr + ::google::protobuf::internal::ParseContext::kSlopBytes) {
          parser_till_end = ::google::protobuf::internal::GreedyStringParser;
          goto string_till_end;
        }
        GOOGLE_PROTOBUF_PARSER_ASSERT(::google::protobuf::internal::StringCheck(ptr, size, ctx));
        ::google::protobuf::internal::InlineGreedyStringParser(object, ptr, size, ctx);
        ptr += size;
        break;
      }
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->EndGroup(tag);
          return ptr;
        }
        auto res = UnknownFieldParse(tag, {_InternalParse, msg},
          ptr, end, msg->_internal_metadata_.mutable_unknown_fields(), ctx);
        ptr = res.first;
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr != nullptr);
        if (res.second) return ptr;
      }
    }  // switch
  }  // while
  return ptr;
string_till_end:
  static_cast<::std::string*>(object)->clear();
  static_cast<::std::string*>(object)->reserve(size);
  goto len_delim_till_end;
len_delim_till_end:
  return ctx->StoreAndTailCall(ptr, end, {_InternalParse, msg},
                               {parser_till_end, object}, size);
}
#else  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
bool ArgReply::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!PROTOBUF_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:os_remote.ArgReply)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // bytes outarg = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (10 & 0xFF)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadBytes(
                input, this->mutable_outarg()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:os_remote.ArgReply)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:os_remote.ArgReply)
  return false;
#undef DO_
}
#endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER

void ArgReply::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:os_remote.ArgReply)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // bytes outarg = 1;
  if (this->outarg().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBytesMaybeAliased(
      1, this->outarg(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:os_remote.ArgReply)
}

::google::protobuf::uint8* ArgReply::InternalSerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:os_remote.ArgReply)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // bytes outarg = 1;
  if (this->outarg().size() > 0) {
    target =
      ::google::protobuf::internal::WireFormatLite::WriteBytesToArray(
        1, this->outarg(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:os_remote.ArgReply)
  return target;
}

size_t ArgReply::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:os_remote.ArgReply)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // bytes outarg = 1;
  if (this->outarg().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::BytesSize(
        this->outarg());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void ArgReply::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:os_remote.ArgReply)
  GOOGLE_DCHECK_NE(&from, this);
  const ArgReply* source =
      ::google::protobuf::DynamicCastToGenerated<ArgReply>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:os_remote.ArgReply)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:os_remote.ArgReply)
    MergeFrom(*source);
  }
}

void ArgReply::MergeFrom(const ArgReply& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:os_remote.ArgReply)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.outarg().size() > 0) {

    outarg_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.outarg_);
  }
}

void ArgReply::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:os_remote.ArgReply)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ArgReply::CopyFrom(const ArgReply& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:os_remote.ArgReply)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ArgReply::IsInitialized() const {
  return true;
}

void ArgReply::Swap(ArgReply* other) {
  if (other == this) return;
  InternalSwap(other);
}
void ArgReply::InternalSwap(ArgReply* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
  outarg_.Swap(&other->outarg_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
}

::google::protobuf::Metadata ArgReply::GetMetadata() const {
  ::google::protobuf::internal::AssignDescriptors(&::assign_descriptors_table_os_5fremote_2eproto);
  return ::file_level_metadata_os_5fremote_2eproto[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace os_remote
namespace google {
namespace protobuf {
template<> PROTOBUF_NOINLINE ::os_remote::ArgRequest* Arena::CreateMaybeMessage< ::os_remote::ArgRequest >(Arena* arena) {
  return Arena::CreateInternal< ::os_remote::ArgRequest >(arena);
}
template<> PROTOBUF_NOINLINE ::os_remote::ArgReply* Arena::CreateMaybeMessage< ::os_remote::ArgReply >(Arena* arena) {
  return Arena::CreateInternal< ::os_remote::ArgReply >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
