sudo: false
os: linux
dist: trusty

services:
  - docker

language: java

jdk:
# Unable to use openjdk6 https://github.com/travis-ci/travis-ci/issues/8199
#  - openjdk6
  - openjdk7
  - oraclejdk8

script:
  - ./scripts/travis-deploy.sh
